name: Gh-Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - name: Ensure build directory exists
        run: mkdir -p build/web
      # - name: Create CNAME file
        # run: touch build/web/CNAME
      # - name: Fill CNAME file
        # run: echo 'choosey.quest' > build/web/CNAME
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          # baseHref: /choosey/
          customArgs: >
            --dart-define="CLIENT_ID=${{ secrets.CLIENT_ID }}" 
            --dart-define="GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          force_orphan: true
